version: '3.7'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"
    container_name: app
    command: ["air"]
    depends_on:
      - db
    networks:
      - backend_network
  db:
    image: postgres:15-alpine
    command: postgres -c log_statement=all
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_DB: "sayaka"
    volumes:
      - ./data-volume:/var/lib/postgresql/data
      - ./data-volume:/var/log
    networks:
        - backend_network
  migration:
    image: flyway/flyway
    volumes:
      - ./database/migration/schema:/flyway/sql
    depends_on:
      - db
    networks:
      - backend_network
networks:
  backend_network:
    external: false