name: Run Migration

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'database/migration/**'
  pull_request:
    branches:
      - main
    types: [ closed ]
    paths:
      - 'database/migration/**'

jobs:
  migration:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: 'Run Migration'
        id: 'migration'
        run: |
          docker run -v $(pwd)/database/migration/schema:/flyway/sql -i --rm flyway/flyway -url=jdbc:mysql://${{secrets.DB_HOST}}:${{secrets.DB_PORT}}/${{secrets.DB_NAME}} -user=${{secrets.DB_USER}} -password=${{secrets.DB_PASSWORD}} migrate